system.action.update_user_action:
  #type: mapping
  type: config_object
  label: 'Update User'
  mapping:
    configuration:
      type: ignore
      label: 'Configuration'
    langcode:
      type: string
      label: 'Langcode'
    status:
      type: boolean
      label: 'Status'
    dependencies:
      type: ignore
      label: 'Dependencies Modules'
    id:
      type: string
      label: 'Id'
    label:
      type: string
      label: 'Label'
    type:
      type: string
      label: 'Type'
    plugin:
      type: string
      label: 'Plugin'
    uuid:
      type: string
      label: 'UUID'
    _core:
      type: ignore
      label: '_Core'

